# Esto es un comentario.
CC = g++
all : prodCons

prodCons : productorConsumidor.c ../shared/framework.h ../shared/definiciones.h 
	cc -o productorConsumidor productorConsumidor.c

clean : 
	rm -rf *o *dat productorConsumidor