# Esto es un comentario.
CC = g++
all : productor supermercado

productor : productor.c ../shared/framework.h ../shared/definiciones.h 
	cc -o productor productor.c
	
clean : 
	rm -rf *o supermercado repositor